/**
 * Единая матрица лимитов длины полей.
 * Синхронизировать с apps/mobile/.../field_limits.dart
 */
export const FIELD_LIMITS = {
  NON_EMPTY_STRING_MIN: 1,
  USER_DISPLAY_NAME_MIN: 3,
  USER_DISPLAY_NAME_MAX: 120,
  USER_PASSWORD_MIN: 8,
  USER_PASSWORD_MAX: 255,
  LOGIN_MIN: 3,
  LOGIN_MAX: 200,
  LOGIN_PASSWORD_MIN: 1,
  EMAIL_MAX: 254,
  PHONE_MAX: 16,
  GEOZONE_NAME_MIN: 1,
  GEOZONE_NAME_MAX: 255,
  GEOZONE_COLOR_MIN: 1,
  GEOZONE_COLOR_MAX: 32,
  GEOZONE_POLYGON_VERTICES_MAX: 15,
  GEOZONE_RULES_JSON_MAX: 16_384,
  TARIFF_NAME_MIN: 1,
  TARIFF_NAME_MAX: 1000,
  /** Максимум для pricePerMinute, pricePerKm, pausePricePerMinute (тариф и геозона). */
  TARIFF_PRICE_MAX: 10_000,
  VIOLATION_DESCRIPTION_MIN: 1,
  VIOLATION_DESCRIPTION_MAX: 1000,
  CAR_STRING_MIN: 1,
  CAR_STRING_MAX: 255,
  CAR_FUEL_MIN: 1,
  CAR_FUEL_MAX: 100,
  CAR_RETURN_TO_SERVICE_COMMENT_MIN: 20,
  CAR_RETURN_TO_SERVICE_COMMENT_MAX: 1000,
  SEARCH_QUERY_MAX: 120,
  TRIP_PLATE_SNAPSHOT_MAX: 32,
  TRIP_DISPLAY_NAME_SNAPSHOT_MAX: 512,
  NOTICE_SUBJECT_MIN: 1,
  NOTICE_SUBJECT_MAX: 500,
  NOTICE_MESSAGE_MIN: 1,
  NOTICE_MESSAGE_MAX: 2000,
  TELEMETRY_SOURCE_MAX: 64,
  VERIFY_EMAIL_CODE_LEN: 6,
} as const;

export type FieldLimits = typeof FIELD_LIMITS;
